### ISSUE TITLE
License content for use on new FoA page

### ISSUE THREAD

**Issue by shaananc** [algorithms-are-fun/amoffat-fan-page#7]
Hi Max,

Would you be happy if we hosted the content from this repo back up at algorithmsare.fun again?
Page is currently the course content, and we'd try and integrate a bit of both.

Cheers,
shaananc
(Lecturer for FoA)

**Comment by bermuda-ut** [comment]
No worries, please feel free to use it! I think _develop_ branch was the main branch I was using here.

Let me know if you plan to fork the repo elsewhere, I'd love to continue contributing at some point (mostly stripping away next-js and react stuff to make it pure HTML+JS, so that students have easier time contributing) Cheers! :)

QQ: Has Alistair stopped teaching FoA?

**Comment by shaananc** [comment]
He's still teaching in full force! I'm just in the other semester.

Pure HTML+JS would be better---current site is using Jekyll as a static site generator

**Comment by shaananc** [comment]
http://algorithmsare.fun/legacy
